# Generated by Django 4.2.7 on 2025-10-19 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Driver's full name", max_length=100)),
                ('phone', models.CharField(help_text='10-digit phone number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('Auto', 'Auto'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], help_text='Type of vehicle', max_length=20)),
                ('vehicle_plate', models.CharField(help_text='Vehicle registration plate number', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the driver is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-driver_id'],
                'indexes': [models.Index(fields=['is_active'], name='drivers_is_acti_d38a80_idx'), models.Index(fields=['vehicle_type'], name='drivers_vehicle_4e8406_idx'), models.Index(fields=['phone'], name='drivers_phone_072555_idx')],
            },
        ),
    ]
